# Generated by Django 3.0.5 on 2020-06-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_auto_20200622_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigneddoctorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Doctor'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='patientid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Patient'),
        ),
    ]
