# Generated by Django 3.0.5 on 2020-10-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_auto_20200622_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigneddoctorid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='patientid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
