# Generated by Django 5.0.6 on 2024-06-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_patient_full_name_alter_department_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
    ]
