# Generated by Django 5.0.6 on 2024-06-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_remove_patient_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
