# Generated by Django 5.0.6 on 2024-06-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_doctor_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentdate',
            new_name='appointmentdate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmenttime',
            new_name='appointmenttime',
        ),
    ]
